os: osx
language: csharp
install:
- nuget restore ./GLTFSerialization/GLTFSerialization.sln
- sudo python2 ./scripts/install-unity.py --package Unity 2017.1.1f1
before_script:
- sudo chmod -R a+rwx /Applications/Unity
- sudo chmod +x ./scripts/export-upm-package.sh
script:
- msbuild ./GLTFSerialization/GLTFSerialization.sln /t:GLTFSerialization /p:TargetFramework=net35
- "./scripts/export-unity-package.sh"
- msbuild ./GLTFSerialization/GLTFSerialization.sln /t:GLTFSerialization
- "./scripts/export-upm-package.sh"
deploy:
  provider: releases
  file: 
  - "./current-package/UnityGLTF.unitypackage"
  - "./current-package/org.khronos.UnityGLTF.zip"
  skip_cleanup: true
  on:
    repo: ei2kpi-ptc/UnityGLTF
    branch: releases
    tags: true
  api-key:
    secure: "e8em7ZXwtuojcjtRZ1ZJY3rblg3iBvrfTgXlEWRnXhBDvV7g8sf2J3E+vd6ESR3CvoyFIcBAV52GsrWnpH9TbpBII3HDY/woJ96UUOCE7W39r6buQDpRk1nXJxRfaDRjcbxjDJinXsromhMmAbdFP1BHr9uF1dDEn4MTlNhQw2imAwU+8z2S5xW5eo/JSvQXSIK3yL7lBiiCMZaCiDYtp648A6BozUnrODlqh5P1MYjawGjdeghx3d38AeJN2AK6eN0Kk9vNTzCNRb/AdDVi7CaZFQuzd4HQfwbbLgwZRp3y2Tjl/jPNf1kzN8S75RhEBHjips8M7Tg9gb6vDxTfR9e0i8doBAxK7i/HrRx8HyBE26sTxfYdbamzkqSVf3UXmDXV+vSzAO5iRMcFka+JCbNy2lHgTb7TVdld3hTiHCHJh+OPGlMsoVb2kFouiPMJ01VlQW0FcDb14GS6t5nUiNwG5KZoJMcg3QGXL8EQ059Hrx4yyZntqT1p2Huo9o4KaOEG1/WFRNJaROtQJDkh554GK/nGW7VIDL10dRpoVpOiznbhL5HfSB4V8+DMlaRDHII1QK/02ZQA3IVo/0CQTg5w+UhVBcGce3VXCqiRXtuQ0k9Iuq4mKUYLmNYkmF25Xppe9s4P+TTrl5NXo9IMqYIPrpx78vkNxfQmE0WUsx8="

